In [180]:
import quimb as qu

# Define the number of sites
L = 10

# Define the interaction strength
J = 1.0

# Initialize the Hamiltonian as a zero matrix
H = qu.hamiltonian(0, dims=[2]*L)

# Add the interaction terms
for i in range(L-1):
    H += J * qu.hamiltonian('Z', [i, i+1], dims=[2]*L)

# Print the Hamiltonian
print(H)


AttributeError: module 'quimb' has no attribute 'hamiltonian'

In [160]:
a1 = random.normal(PRNGKey(0), (4,))
w1 = random.normal(PRNGKey(1), (4, 4))
w2 = random.normal(PRNGKey(2), (4, 4))
w3 = random.normal(PRNGKey(3), (4, 4))

In [161]:
def f(a1):
    a2 = jnp.dot(w1, a1)
    a2a = jnp.sin(a2)
    a3 = jnp.dot(w2, a2a)
    a3a = jnp.sin(a3)
    a4 = jnp.dot(w3, a3a)
    return a4

In [168]:
a2 = jnp.dot(w1, a1)
a2a = jnp.sin(a2)
a3 = jnp.dot(w2, a2a)
a3a = jnp.sin(a3)
a4 = jnp.dot(w3, a3a)

In [169]:
jnp.trace(jacobian_matrix_)

Array(1.0969937, dtype=float32)

In [170]:
print(w1*np.arange(10))

ValueError: Incompatible shapes for broadcasting: shapes=[(4, 4), (10,)]

In [171]:
tmp1 = jnp.dot(w3*jnp.cos(a3), w2)
a3prime = jnp.dot(tmp1*jnp.cos(a2), w1)
print(jnp.trace(a3prime))

1.0969937


In [172]:
tmp = jnp.einsum('ab,b,bc-> ac', w3, jnp.cos(a3), w2)
final = jnp.einsum('ab,b,bc-> ac', tmp, jnp.cos(a2), w1)
print(jnp.trace(final))


1.0969942


In [173]:
def h(a2a):
    a3 = jnp.dot(w2, a2a)
    a3a = jnp.sin(a3)
    a4 = jnp.dot(w3, a3a)
    return a4
def k(a3):
    a3a = jnp.sin(a3)
    a4 = jnp.dot(w3, a3a)
    return a4

In [174]:
jacobian_matrix_ = jax.jacfwd(h)(a2a)
jacobian_matrix__ = jax.jacfwd(k)(a3)
print(jacobian_matrix_)
print(jacobian_matrix__)

[[ 1.6747543  -0.99533826  0.84662145 -0.7347188 ]
 [ 0.7806493  -0.5360816   0.4985824  -0.8108842 ]
 [ 0.37664634 -0.42467034 -0.14767969 -0.7029713 ]
 [-0.91273946  0.6144608  -1.3632437  -0.30421022]]
[[ 1.6764153   0.8682407  -0.4822424   0.06036609]
 [ 0.922981    0.7227854  -0.05123625 -0.7770437 ]
 [ 0.68734634  0.12545048 -0.3690089  -0.340322  ]
 [-0.25852078 -0.83786345 -0.23895714 -0.31750754]]


In [179]:
print(jnp.dot((w3*jnp.cos(a3)), w2))
print(w3*jnp.cos(a3))


[[ 1.6747544  -0.9953382   0.84662145 -0.7347188 ]
 [ 0.7806493  -0.5360816   0.4985824  -0.8108842 ]
 [ 0.37664637 -0.42467028 -0.14767972 -0.7029712 ]
 [-0.9127395   0.61446095 -1.3632438  -0.3042102 ]]
[[ 1.6764153   0.8682407  -0.4822424   0.06036609]
 [ 0.922981    0.7227854  -0.05123625 -0.7770437 ]
 [ 0.68734634  0.12545048 -0.3690089  -0.340322  ]
 [-0.25852078 -0.83786345 -0.23895714 -0.31750754]]


In [176]:
a2

Array([ 1.0488347, -0.8257268, -0.9081995,  0.3947487], dtype=float32)

In [177]:
jnp.dot(w1,a1)

Array([ 1.0488347, -0.8257268, -0.9081995,  0.3947487], dtype=float32)