In [29]:
import jax.random
import numpy as np
import matplotlib.pyplot as plt
matrix_list = []
for i in range(64):
    print(np.load("mps_tensors/tensor_"+str(i+1)+".npy"))
    matrix_list.append(np.load("mps_tensors/tensor_"+str(i+1)+".npy"))

[[-7.07106781e-01 -7.21644966e-16]
 [-7.21644966e-16  7.07106781e-01]]
[[[ 0.62239202 -0.33560122]
  [-0.33560122 -0.62239202]]

 [[ 0.62239202 -0.33560122]
  [ 0.33560122  0.62239202]]]
[[[ 7.07106781e-01 -8.32149003e-15]
  [-1.10669323e-15 -7.07106781e-01]]

 [[ 5.90789184e-01 -3.88546188e-01]
  [ 3.88546188e-01  5.90789184e-01]]]
[[[ 0.53171178 -0.4661358 ]
  [ 0.4661358   0.53171178]]

 [[ 0.68162629  0.1881106 ]
  [ 0.1881106  -0.68162629]]]
[[[ 0.39021658 -0.58968722]
  [ 0.58968722  0.39021658]]

 [[-0.70076067 -0.09452238]
  [-0.09452238  0.70076067]]]
[[[-7.07106781e-01  4.71027738e-16]
  [-2.03579109e-15  7.07106781e-01]]

 [[ 5.32232785e-01 -4.65540828e-01]
  [ 4.65540828e-01  5.32232785e-01]]]
[[[ 7.07106781e-01  8.75326546e-15]
  [ 5.73542621e-15 -7.07106781e-01]]

 [[-4.65540828e-01  5.32232785e-01]
  [-5.32232785e-01 -4.65540828e-01]]]
[[[ 7.07106781e-01 -1.80560633e-15]
  [ 5.54551204e-15 -7.07106781e-01]]

 [[-5.32232785e-01  4.65540828e-01]
  [-4.65540828e-01 -5.32232

In [30]:
print(matrix_list[-1] @ matrix_list[-1].transpose())
for i in (np.arange(62)+2):
    print(np.einsum('ijk, ilk -> jl', matrix_list[-i].conj(), matrix_list[-i]))
    

[[1.00000000e+00 7.33532768e-18]
 [7.33532768e-18 1.00000000e+00]]
[[ 1.00000000e+00 -3.46944695e-18]
 [-3.46944695e-18  1.00000000e+00]]
[[ 1.00000000e+00 -7.97972799e-17]
 [-7.97972799e-17  1.00000000e+00]]
[[ 1.0000000e+00 -4.4408921e-16]
 [-4.4408921e-16  1.0000000e+00]]
[[1.00000000e+00 1.38777878e-17]
 [1.38777878e-17 1.00000000e+00]]
[[ 1.00000000e+00 -1.80411242e-16]
 [-1.80411242e-16  1.00000000e+00]]
[[1.00000000e+00 1.11022302e-16]
 [1.11022302e-16 1.00000000e+00]]
[[ 1.0000000e+00 -4.4408921e-16]
 [-4.4408921e-16  1.0000000e+00]]
[[ 1.00000000e+00 -1.11022302e-16]
 [-1.11022302e-16  1.00000000e+00]]
[[1.00000000e+00 2.22044605e-16]
 [2.22044605e-16 1.00000000e+00]]
[[1. 0.]
 [0. 1.]]
[[1.00000000e+00 5.55111512e-17]
 [5.55111512e-17 1.00000000e+00]]
[[ 1.00000000e+00 -1.66533454e-16]
 [-1.66533454e-16  1.00000000e+00]]
[[1. 0.]
 [0. 1.]]
[[1.00000000e+00 2.77555756e-17]
 [2.77555756e-17 1.00000000e+00]]
[[1.00000000e+00 1.11022302e-16]
 [1.11022302e-16 1.00000000e+00]]
[[ 1

In [26]:
h0 = np.ones(2)
(matrix_list[0] @ matrix_list[0].conj().transpose())

array([[5.0000000e-01, 2.6271174e-31],
       [2.6271174e-31, 5.0000000e-01]])

In [31]:
print(matrix_list[0])

[[-7.07106781e-01 -7.21644966e-16]
 [-7.21644966e-16  7.07106781e-01]]


In [29]:
matrix = np.load("mps_tensors/tensor_2.npy")
print(matrix)
print(np.linalg.eigvals(matrix[0]))
print(np.linalg.eigvals(matrix[1]))
print(np.linalg.eigv(matrix))

[[[ 0.62239202 -0.33560122]
  [-0.33560122 -0.62239202]]

 [[ 0.62239202 -0.33560122]
  [ 0.33560122  0.62239202]]]
[ 0.70710678 -0.70710678]
[0.62239202+0.33560122j 0.62239202-0.33560122j]
(array([[ 0.70710678+0.j        , -0.70710678+0.j        ],
       [ 0.62239202+0.33560122j,  0.62239202-0.33560122j]]), array([[[ 9.69586312e-01+0.j        ,  2.44749636e-01+0.j        ],
        [-2.44749636e-01+0.j        ,  9.69586312e-01+0.j        ]],

       [[-1.84243051e-16+0.70710678j, -1.84243051e-16-0.70710678j],
        [ 7.07106781e-01+0.j        ,  7.07106781e-01-0.j        ]]]))


In [35]:
import jax
import jax.numpy as jnp
jnp.linalg.norm(jnp.ones((3, 4)), axis = 1)

Array([2., 2., 2.], dtype=float32)

In [55]:
jnp.repeat(jnp.arange(3), 3, axis = 0)

Array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int32)

In [50]:
jnp.angle(jnp.array([3+4*1j, 2+3*1j]))

Array([0.9272952 , 0.98279375], dtype=float32)

In [59]:
import itertools
def generate_combinations(length):
    set1 = [1] * length
    set2 = [3] * length
    combinations = list(itertools.product(*zip(set1, set2)))
    return jnp.array(combinations)
jnp.repeat(generate_combinations(2), 2, axis = 0)

Array([[1, 1],
       [1, 1],
       [1, 3],
       [1, 3],
       [3, 1],
       [3, 1],
       [3, 3],
       [3, 3]], dtype=int32)

In [52]:
jnp.zeros(3, dtype=complex)

Array([0.+0.j, 0.+0.j, 0.+0.j], dtype=complex64)